/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -m -a hudadaptor -i huddbus.h -l HUDDBus /home/joseph/ubuntu-tv/shell/app/hud.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "hudadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class HUDAdaptor
 */

HUDAdaptor::HUDAdaptor(HUDDBus *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

HUDAdaptor::~HUDAdaptor()
{
    // destructor
}

bool HUDAdaptor::active() const
{
    // get the value of property active
    return qvariant_cast< bool >(parent()->property("active"));
}

void HUDAdaptor::setActive(bool value)
{
    // set the value of property active
    parent()->setProperty("active", QVariant::fromValue(value));
}

int HUDAdaptor::screen() const
{
    // get the value of property screen
    return qvariant_cast< int >(parent()->property("screen"));
}


#include "hudadaptor.moc"
